# This is a Docker Compose file for a Node.js application with a backend and frontend service.
# It defines the services, their build configurations, environment variables, ports, and health checks.

services:
  backend:
    build:
      context: .                                # Expanded context to project root
      dockerfile: ./docker/api/Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=5000
      - IS_LOCAL=false
    env_file:
      - ./jamz-server/.env.local  
    ports:
      - "5050:5000"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .                                # Expanded context to project root
      dockerfile: ./docker/frontend/Dockerfile.prod
    environment:
      - NODE_ENV=production
      - IS_LOCAL=false
      - VITE_API_BASE=http://backend:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
