# docker-compose.yml
# This file is used to define the services, networks, and volumes for the TrafficJamz application.
# It includes configurations for both production and development environments.

version: '3'
services:
  frontend:
    image: trafficjamz-frontend
    ports:
      - "3000:3000"
  backend:
    image: trafficjamz-backend
    ports:
      - "5000:5000"