version: '3.8'

services:
  backend:
    build:
      context: ./jamz-server
      dockerfile: ../docker/api/Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=5000
      - IS_LOCAL=false
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./jamz-client-vite
      dockerfile: ../docker/frontend/Dockerfile.prod
    environment:
      - NODE_ENV=production
      - IS_LOCAL=false
      - VITE_API_BASE=http://backend:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
