# ============================================================================
# File: docker/frontend/docker-compose.prod.yml
# Purpose: Standalone compose file to build and run the TrafficJamz frontend
# Usage:
#   From the project root:
#     docker compose -f docker/frontend/docker-compose.prod.yml build
#     docker compose -f docker/frontend/docker-compose.prod.yml up -d
#
# Notes:
# - Uses Dockerfile.prod to build the production frontend image.
# - Loads environment variables from .env.prod in this same folder.
# - Maps frontend to host ports 3000 (HTTP) and 3443 (HTTPS).
# - For full stack (API, DB, Kafka, etc.), use the root docker-compose.yml.
# ============================================================================

services:
  frontend:
    container_name: trafficjamz-frontend
    build:
      context: ../..                       # project root relative to docker/frontend/
      dockerfile: docker/frontend/Dockerfile.prod
    env_file:
      - ./.env.prod                        # env file is in the same folder as this compose file
    ports:
      - "3000:80"
      - "3443:443"
    restart: unless-stopped
