# File: docker/frontend/docker-compose.prod.yml
# Purpose: Build and run the TrafficJamz frontend in isolation
# Usage:
#   docker compose -f docker/frontend/docker-compose.prod.yml up -d --build client
# Notes:
#   - Uses the same service name ("client") as the root compose file
#   - Useful for rapid UI iteration without spinning up the full stack

services:
  client:
    build:
      context: ../..                # project root
      dockerfile: docker/frontend/Dockerfile.prod
    image: trafficjamz-client:latest
    container_name: trafficjamz-client
    ports:
      - "8080:80"
      - "3443:443"
    env_file:
      - ./.env.prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
