#!/usr/bin/env node

/**
 * Quick Test Runner - Runs essential tests and generates report
 */

import { exec } from 'child_process';
import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TEST_URL = process.env.TEST_URL || 'https://jamz.v2u.us';

// Quick test projects (focus on most common browsers)
const PROJECTS = [
  { name: 'chromium-desktop', display: 'Chrome Desktop' },
  { name: 'firefox-desktop', display: 'Firefox Desktop' },
  { name: 'webkit-desktop', display: 'Safari Desktop' },
  { name: 'mobile-safari', display: 'Safari iOS' },
];

async function runProjectTests(project) {
  return new Promise((resolve) => {
    console.log(`\n Testing ${project.display}...`);
    
    // Windows-compatible command
    const isWindows = process.platform === 'win32';
    const cmd = isWindows 
      ? `npx playwright test smoke.spec.js --project=${project.name} --reporter=json --timeout=30000 --retries=0`
      : `TEST_URL=${TEST_URL} npx playwright test smoke.spec.js --project=${project.name} --reporter=json --timeout=30000 --retries=0`;
    
    const startTime = Date.now();
    const execOptions = { 
      cwd: path.join(__dirname, '..'), 
      maxBuffer: 10 * 1024 * 1024,
      env: { ...process.env, TEST_URL: TEST_URL }
    };
    
    exec(cmd, execOptions, (error, stdout, stderr) => {
      const duration = Date.now() - startTime;
      
      // Debug output
      if (error) {
        console.log(`  Error executing: ${error.message}`);
      }
      if (stderr && stderr.trim()) {
        console.log(`  Stderr: ${stderr.substring(0, 200)}`);
      }
      
      const result = {
        project: project.name,
        display: project.display,
        passed: 0,
        failed: 0,
        skipped: 0,
        total: 0,
        duration: duration / 1000,
        status: 'unknown'
      };

      try {
        if (stdout) {
          // Debug: Show what we received
          console.log(`  Stdout length: ${stdout.length} chars`);
          if (stdout.trim()) {
            console.log(`  First 200 chars: ${stdout.substring(0, 200)}`);
          }
          
          const jsonOutput = JSON.parse(stdout);
          
          if (jsonOutput.suites) {
            jsonOutput.suites.forEach(suite => {
              suite.specs?.forEach(spec => {
                result.total++;
                const testResult = spec.tests?.[0]?.results?.[0];
                if (testResult) {
                  if (testResult.status === 'passed') result.passed++;
                  else if (testResult.status === 'failed') result.failed++;
                  else if (testResult.status === 'skipped') result.skipped++;
                }
              });
            });
          }
        }
        
        if (result.total === 0 && error) {
          result.status = '❌ Error';
        } else if (result.failed === 0 && result.passed > 0) {
          result.status = '✅ Pass';
        } else if (result.failed > 0 && result.passed > result.failed) {
          result.status = '⚠️ Partial';
        } else {
          result.status = '❌ Fail';
        }
        
      } catch (e) {
        console.log(`  Parse error: ${e.message}`);
        result.status = '❌ Parse Error';
      }

      console.log(`  ${result.status} - ${result.passed}/${result.total} passed (${result.duration.toFixed(1)}s)`);
      resolve(result);
    });
  });
}

async function generateReport(results) {
  const timestamp = new Date().toLocaleString('en-US', { 
    timeZone: 'America/Chicago',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const totalPassed = results.reduce((sum, r) => sum + r.passed, 0);
  const totalFailed = results.reduce((sum, r) => sum + r.failed, 0);
  const totalTests = results.reduce((sum, r) => sum + r.total, 0);
  const totalDuration = results.reduce((sum, r) => sum + r.duration, 0);

  const report = `# Test Run Report

**Date:** ${timestamp}
**Test URL:** ${TEST_URL}
**Total Tests:** ${totalTests}
**Passed:** ${totalPassed} ✅
**Failed:** ${totalFailed} ❌
**Duration:** ${totalDuration.toFixed(1)}s

## Results by Browser

| Browser | Status | Passed | Failed | Total | Duration |
|---------|--------|--------|--------|-------|----------|
${results.map(r => 
  `| ${r.display} | ${r.status} | ${r.passed} | ${r.failed} | ${r.total} | ${r.duration.toFixed(1)}s |`
).join('\n')}

## Overall Status

${totalFailed === 0 ? '✅ All tests passing!' : 
  totalPassed > totalFailed ? '⚠️ Some failures detected' : 
  '❌ Critical failures detected'}

---
*Generated by automated test runner*
`;

  // Save report
  const reportPath = path.join(__dirname, '../../test-results-summary.md');
  await fs.writeFile(reportPath, report);
  console.log(`\n📊 Report saved to: test-results-summary.md`);
  
  return report;
}

async function main() {
  console.log('🧪 TrafficJamz Quick Test Suite\n');
  console.log(`Testing: ${TEST_URL}\n`);
  console.log('='.repeat(50));

  const results = [];
  for (const project of PROJECTS) {
    const result = await runProjectTests(project);
    results.push(result);
  }

  console.log('\n' + '='.repeat(50));
  const report = await generateReport(results);
  console.log('\n' + report);
}

main().catch(console.error);
