apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficjamz-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trafficjamz-frontend
  template:
    metadata:
      labels:
        app: trafficjamz-frontend
    spec:
      containers:
        - name: trafficjamz-frontend
          image: trafficjamz-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
